[build]
  base = "frontend"
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_FLAGS = "--no-frozen-lockfile"

[[plugins]]
  package = "@netlify/plugin-nextjs"